# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8cdd062cd4c14866f0d2b4eae7b80f48ce843b3e3b4bdec65c5849a18680b73a2a680d72defc90af315150e427e8611b267ae0692961059bd1518f806f25172

test:
  secret_key_base: d864d991f05aca7c5be8a6bf087e4c705cc3d0967468e2ba90a2843205126bb14b6d4d8ce190dabb2e9757509c7feeac25945e60ce1fb6206c0ed2cf1fbc1c2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
