require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcompanamientosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Acompanamiento. As you add validations to Acompanamiento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcompanamientosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all acompanamientos as @acompanamientos" do
      acompanamiento = Acompanamiento.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:acompanamientos)).to eq([acompanamiento])
    end
  end

  describe "GET show" do
    it "assigns the requested acompanamiento as @acompanamiento" do
      acompanamiento = Acompanamiento.create! valid_attributes
      get :show, {:id => acompanamiento.to_param}, valid_session
      expect(assigns(:acompanamiento)).to eq(acompanamiento)
    end
  end

  describe "GET new" do
    it "assigns a new acompanamiento as @acompanamiento" do
      get :new, {}, valid_session
      expect(assigns(:acompanamiento)).to be_a_new(Acompanamiento)
    end
  end

  describe "GET edit" do
    it "assigns the requested acompanamiento as @acompanamiento" do
      acompanamiento = Acompanamiento.create! valid_attributes
      get :edit, {:id => acompanamiento.to_param}, valid_session
      expect(assigns(:acompanamiento)).to eq(acompanamiento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acompanamiento" do
        expect {
          post :create, {:acompanamiento => valid_attributes}, valid_session
        }.to change(Acompanamiento, :count).by(1)
      end

      it "assigns a newly created acompanamiento as @acompanamiento" do
        post :create, {:acompanamiento => valid_attributes}, valid_session
        expect(assigns(:acompanamiento)).to be_a(Acompanamiento)
        expect(assigns(:acompanamiento)).to be_persisted
      end

      it "redirects to the created acompanamiento" do
        post :create, {:acompanamiento => valid_attributes}, valid_session
        expect(response).to redirect_to(Acompanamiento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acompanamiento as @acompanamiento" do
        post :create, {:acompanamiento => invalid_attributes}, valid_session
        expect(assigns(:acompanamiento)).to be_a_new(Acompanamiento)
      end

      it "re-renders the 'new' template" do
        post :create, {:acompanamiento => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acompanamiento" do
        acompanamiento = Acompanamiento.create! valid_attributes
        put :update, {:id => acompanamiento.to_param, :acompanamiento => new_attributes}, valid_session
        acompanamiento.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested acompanamiento as @acompanamiento" do
        acompanamiento = Acompanamiento.create! valid_attributes
        put :update, {:id => acompanamiento.to_param, :acompanamiento => valid_attributes}, valid_session
        expect(assigns(:acompanamiento)).to eq(acompanamiento)
      end

      it "redirects to the acompanamiento" do
        acompanamiento = Acompanamiento.create! valid_attributes
        put :update, {:id => acompanamiento.to_param, :acompanamiento => valid_attributes}, valid_session
        expect(response).to redirect_to(acompanamiento)
      end
    end

    describe "with invalid params" do
      it "assigns the acompanamiento as @acompanamiento" do
        acompanamiento = Acompanamiento.create! valid_attributes
        put :update, {:id => acompanamiento.to_param, :acompanamiento => invalid_attributes}, valid_session
        expect(assigns(:acompanamiento)).to eq(acompanamiento)
      end

      it "re-renders the 'edit' template" do
        acompanamiento = Acompanamiento.create! valid_attributes
        put :update, {:id => acompanamiento.to_param, :acompanamiento => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acompanamiento" do
      acompanamiento = Acompanamiento.create! valid_attributes
      expect {
        delete :destroy, {:id => acompanamiento.to_param}, valid_session
      }.to change(Acompanamiento, :count).by(-1)
    end

    it "redirects to the acompanamientos list" do
      acompanamiento = Acompanamiento.create! valid_attributes
      delete :destroy, {:id => acompanamiento.to_param}, valid_session
      expect(response).to redirect_to(acompanamientos_url)
    end
  end

end
